### ISSUE TITLE
Hacer funcionar signup y forgoten password

### ISSUE THREAD

**Issue by ghost** [arkaitzz/sg_ils#1]
- [x] Limpiar menú de cabecera: items de la barra de menú y solo dejar Inicio.
- [x] Eliminar acciones innecesarias relacionadas con el menú de cabecera: search. (lo dejo sin tocar por si nos viene bien en un futuro).
- [x] Configuración básica de action mailer.
- [x] Crear plantilla de correo. (Nota sobre el envío e I18n: utilizar los locales para determinar la plantilla a enviar: http://guides.rubyonrails.org/v4.2/action_mailer_basics.html#mailer-views y https://stackoverflow.com/questions/3997148/set-actionmailer-to-use-foo-fr-erb-when-i18n-locale-is-set-to-en)
- [x] Enviar correos multipart: text y html
- [x] Adjuntar logo al pié cuando el correo es HTML, ¿y adjunto cuando es texto?.
- [x] Comprobar envío de correo en forgoten y enganchar en signup.
- [x] Al enviar correo Signup: redirigir al inicio en vez de a la vista del perfil.
- [x] Corregir, mejorar detalles básicos de estas vistas:
  - [x] Forgot_password
  - [x] Email_sent
  - [x] Registration
  - [x] Login: entre otras, eliminar el "Remember me".
  - [x] Reset password
  - [x] User view (profile)

**Comment by arkaitzz** [comment]
¿Qué mail vamos a usar para el envio?

**Comment by ghost** [comment]
Para desarrollo utilicemos el que queramos: lo que me indicabas de conectar mas adelante con Maps de Google lo podemos estudiar llegado el momento. En producción utilizaremos de momento uno del dominio euskal-gorrak.org de momento y si se da el caso de los mapas, utilizamos alguno que tengan o les creamos uno (supongo) :)

**Comment by ghost** [comment]
Realizando esta tarea, me ha salido la necesidad de aclarar el ciclo básico de usuario: cuando entra como invitado a la aplicación, cuando quiere loguearse, cuando quiere crearse una cuenta, etc. Necesito que lo acordemos. Si te parece, hago un dibujo y comentamos.

**Comment by arkaitzz** [comment]
perfect

**Comment by ghost** [comment]
![20180108_001](https://user-images.githubusercontent.com/204091/34671685-c9acadf0-f47b-11e7-9f31-8f39cd670b67.jpg)
A ver que te parece esto: si quieres hacemos una pequeña videollamada (10 min. máximo) y concretamos.

**Comment by arkaitzz** [comment]
me parece perfect! :100: skype si quieres comentar.
